### PR TITLE
upgrade: alliance v0.3.4

### PR DESCRIPTION
**Pull request by javiersuweijie**
Upgrade alliance to use v0.3.4. This is a consensus breaking change

### CODE REVIEW

**Review by emidev98 — APPROVED** [review]
Good PR,

**Comment by hoank101** [comment]
hi @javiersuweijie 
i see everything look good, can you show me why consensus breaking?

**Comment by javiersuweijie** [comment]
> hi @javiersuweijie i see everything look good, can you show me why consensus breaking?

Hey! The upgrade to alliance https://github.com/terra-money/alliance/releases/tag/v0.4.3 has some changes to how rewards are calculated.

**Comment by hoank101** [comment]
> > hi @javiersuweijie i see everything look good, can you show me why consensus breaking?
> 
> Hey! The upgrade to alliance https://github.com/terra-money/alliance/releases/tag/v0.4.3 has some changes to how rewards are calculated.

thank you

**Pull request merged**
