### PR TITLE
[Bump] cosmwasm to v0.15.0

### PR DESCRIPTION
**Pull request by YunSuk-Yeo**
## Summary of changes

Keep follow [wasmd](https://github.com/CosmWasm/wasmd/pull/548) updates.

Reply response data overwrite sdk contract execution response data [wasmd PR](https://github.com/CosmWasm/wasmd/pull/548/commits/b0885b03c907e36fb3c80913ed29d526164ade49)

### Wasm Events
* Deprecate `from_contract` events
We still emit `from_contract` events, but it will be deprecated in the next version. also `from_contract` is not passed to contract at `reply`. 

* Introduce `wasm` events
Please use `wasm` events instead of `from_contract` events.

* Introduce `wasm_` prefixed events
Now the contracts can emit the `Events` with its own `type`, not just `Attributes`.
  ```
  {
    Type: "type1",
      Attributes: wasmvmtypes.EventAttributes{
        {Key: "key1", Value: "value1"},
        {Key: "key2", Value: "value2"},
        {Key: "key3", Value: "value3"},
    },
  }
  ```

### CheckList
- [x] Messages and submessages are merged; the replyOn type now got a new "never" case for the fire and forget messages
- [x] replyOn is not an integer but supports the Stringer interface (i.e. .String())
- [x] The interface version was bumped from interface_version_5 to interface_version_6 such that CosmWasm 0.15.0 contracts need to be used
- [x] In some Wasm messages "send" was renamed to "funds" for consistency
- [ ] The IBC acknowledgement type was changed slightly
- [x] There is a new Gov message (MsgVote) that needs to be connected
- [x] Deserializing contract results now cost gas. This needs to be configured in a new argument of vm.Execute and friends. We messed up storing the value in the vm instance, such that it needs to be passed to every call. Sorry for that! The deserialization cost is in gas per byte. It is a fraction, so you can use 20/1, 10/1, 1/1, 1/2, 1/30, ... in there.
- [x] Contract responses now contain events. The exiting Attributes should go into a main wasm event as before. All other events should be added with a wasm- prefix on the event type.
- [x] Set correct release version in go.mod
- [x] Upgrade Dockerfile with proper version checksum

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by hanjukim** [comment]
wasm.proto needs to be updated (max_contract_data_size, event_params has been deleted)

**Review by hanjukim — CHANGES_REQUESTED** [review]
wasm.proto needs to be updated (max_contract_data_size, event_params has been deleted)

**Comment by hanjukim** [comment]
oh nvm. Why did test fail?

**Comment by YunSuk-Yeo** [comment]
> wasm.proto needs to be updated (max_contract_data_size, event_params has been deleted)

It seems removed

**Comment by YunSuk-Yeo** [comment]
> oh nvm. Why did test fail?

that is due to randomness of golfing json string comparison. Maybe removing array from the migration solve the problem

**Review by hanjukim — APPROVED** [review]

**Pull request merged**
